---
title: "ICE COVID-19 Scrape"
author: "Nathan Craig"
output:
  html_document:
    df_print: paged
---

```{r}
library(rvest)
library(tidyverse)
```

```{r}
url <- "https://www.ice.gov/coronavirus"
page <- read_html(url)
```

```{r}
# Get the total detained population as a string
total_detained <-
  html_nodes(page, "table") %>% 
    html_table() %>% 
    pluck(1) %>% 
    pluck(1) %>% 
    str_remove_all(.,"\t") %>% 
    str_remove_all(.,"DETAINED POPULATION1\nAS OF ") %>% 
    str_split(., "\n\n", n = 2) %>% 
    map(.,2) %>% 
    str_c()

# Get the total COVID cases in custody
total_covid <- 
  html_nodes(page, "table") %>% 
    html_table() %>% 
    pluck(1) %>% 
    pluck(2) %>% 
    str_remove_all(.,"\t") %>% 
    str_remove_all(.,"COVID-19 POSITIVE CASES CURRENTLY IN CUSTODY2\nUNDER ISOLATION OR MONITORING AS OF ") %>% 
    str_split(., "\n\n", n = 2) %>% 
    map(.,2) %>% 
    str_c()

# Total tested
total_tested <- 
  html_nodes(page, "table") %>% 
  html_table() %>% 
  pluck(1) %>% 
  pluck(3) %>% 
  str_remove_all(.,"\t") %>% 
  str_remove_all(.,"DETAINEES TESTED\nAS OF ") %>% 
  str_split(., "\n\n", n = 2) %>% 
  map(.,2) %>% 
  str_c()
  

covid_summary_totals <- 
tibble(Date = format(Sys.time(), "%d/%m/%Y"),`Total Detained` = total_detained, `Total COVID-19` = total_covid, `Total Tested` = total_tested)
covid_summary_totals

```




```{r}
# Get the table of cases by facility
confirmed_cases <- html_nodes(page, "table") %>% 
  html_table() %>% 
  pluck(2) %>% 
  filter(!grepl("Field Office", `Confirmed cases currently under isolation or monitoring`)) %>% 
  filter(!grepl("Endeavors", `Confirmed cases currently under isolation or monitoring`)) %>% 
  filter(!grepl("TOTAL", `Custody/AOR/Facility`))


confirmed_cases <- 
mutate(confirmed_cases, Date = format(Sys.time(), "%d/%m/%Y"), .before = `Custody/AOR/Facility`)
```
```{r}

```



```{r}
write_csv(confirmed_cases,
          "./data/covid_by_facility.csv",
          append = TRUE,
          col_names = FALSE)


write_csv(covid_summary_totals,
          "./data/covid_summaries.csv",
          append = TRUE,
          col_names = FALSE)
```


