---
title: "Wayback Scrape"
author: "Nathan Craig"
output:
  html_document:
    df_print: paged
---

```{r}
library(rvest)
library(tidyverse)
library(lubridate)
```

```{r}
urls <- 
read_lines("Wayback_URL_List.txt")
urls
```

```{r}
# Put the pages into a variable. The output is a list.
page <- 
  map(urls, ~read_html(.x) %>% 
        html_nodes("table") %>% 
        html_text())

```

# COVID-19 Summaries

```{r}
# Get the page date. The output is a list
page_date <- 
urls %>% 
  map(., ~str_remove_all(., "https://web.archive.org/web/")) %>% 
  map(., ~str_remove_all(.,"/https://www.ice.gov/coronavirus")) %>% 
  str_sub(.,start = 1, end = 8)
```


```{r}
# Get the total detained population as a string
total_detained <- 
page %>% 
  map(.x, .f = pluck(1)) %>% 
  str_remove_all(.,"\n\t\t\tDETAINED POPULATION1\n\t\t\tAS OF ") %>% 
  str_remove_all(., "\t\t\t\n\t\t\t\n\t\t\tCOVID-19 POSITIVE CASES CURRENTLY IN CUSTODY2\n\t\t\tUNDER ISOLATION OR MONITORING AS OF ") %>% 
  str_remove_all(., "\t\t\t\n\t\t\t\n\t\t\tDETAINEES TESTED\n\t\t\tAS OF ") %>% 
  str_remove_all(., "\n\t\t\t\n\t\t") %>% 
  str_remove_all(., "\n\t\t\t") %>% 
  str_split(., "\n") %>% 
  map(.,2) %>% 
  str_c()

# Total tested
total_tested <-
  page %>% 
  map(.x, .f = pluck(1)) %>% 
  str_remove_all(.,"\n\t\t\tDETAINED POPULATION1\n\t\t\tAS OF ") %>% 
  str_remove_all(., "\t\t\t\n\t\t\t\n\t\t\tCOVID-19 POSITIVE CASES CURRENTLY IN CUSTODY2\n\t\t\tUNDER ISOLATION OR MONITORING AS OF ") %>% 
 str_remove_all(., "\t\t\t\n\t\t\t\n\t\t\tDETAINEES TESTED\n\t\t\tAS OF ") %>% 
 str_remove_all(., "\n\t\t\t\n\t\t") %>% 
 str_remove_all(., "\n\t\t\t") %>% 
 str_split(., "\n") %>%
 map(.,6)%>% 
 str_c()


out_table1 <- 
  tibble(
  Date = page_date,
  `Total Detained` = total_detained,
  `Total Tested` = total_tested
  ) %>% 
  mutate(ID = row_number(),
         Date = ymd(Date))
out_table1
```


```{r}
# Get total deaths and Total COVID-19
tibble_list <- 
map(urls, ~read_html(.x) %>% 
      html_nodes("table") %>% 
      html_table() %>% 
      pluck(2) %>% 
      filter(grepl("TOTAL", `Custody/AOR/Facility`)) %>% 
      select(., -`Custody/AOR/Facility`) %>% 
      rename(`Total COVID-19 Confirmed in Custody` = `Confirmed cases currently under isolation or monitoring`) %>% 
      rename(`Total Deaths` = `Detainee deaths3`) %>% 
      rename(`Total Cumulative COVID-19`=`Total confirmed COVID-19 cases4`)
    
    )


# Take the list of tibbles and bind them together in a single tibble
# and add an ID number
out_table2 <- 
bind_rows(
  map(tibble_list,
    ~pluck(.x)
    )) %>% 
  mutate(ID = row_number(), .before = `Total COVID-19 Confirmed in Custody`)
out_table2
```


```{r}
# Bind the tables and join them
covid_summary_totals <- 
left_join(out_table1, out_table2, by = "ID") %>% 
  select(-ID) %>% 
  relocate(`Total Cumulative COVID-19`, .after = `Total Detained`) %>% 
  relocate(`Total Deaths`, .after = `Total Tested`)
covid_summary_totals
```

```{r}
write_csv(covid_summary_totals,
          "./../data/covid_summaries_tmp.csv",
          append = TRUE,
          col_names = FALSE)
```


# COVID-19 Facility Numbers

```{r}
# Get the table of cases by facility
# confirmed_cases <- html_nodes(page, "table") %>% 
#   html_table() %>% 
#   pluck(2) %>% 
#   filter(!grepl("Field Office", `Confirmed cases currently under isolation or monitoring`)) %>% 
#   filter(!grepl("Endeavors", `Confirmed cases currently under isolation or monitoring`)) %>% 
#   filter(!grepl("TOTAL", `Custody/AOR/Facility`))
# 
# 
# confirmed_cases <- 
# mutate(confirmed_cases, Date = format(Sys.time(), "%d/%m/%Y"), .before = `Custody/AOR/Facility`)
# confirmed_cases
```


